--- 
- name: 사용자 삭제
  hosts: all
  vars_files:
  - vars/secret.yml
  tasks:
  - name: 다중 사용자 삭제
    user: 
      name: "{{ item.name }}"
      state: absent
      remove: yes
    with_items: 
    - "{{ newusers }}"
# echo 'soldesk1.' > vault-pass
# chmod 600 vault-pass
# anp restore_createusers.yml --vault-password-file=vault-pass
