- name: DB 패키지 삭제
  hosts: all
  tasks:
  - name: 서비스 종료
    service:
      name: mariadb
      state: started
      enabled: no  

  - name: DB 패키지 삭제
    yum:
      name: "{{ pkg_db }}"
      state: absent
    vars:
      pkg_db:
      - mariadb-server
      - python3-PyMySQL
    when: ansible_distribution == 'CentOS'


